# Variable 'buildtrigered' was defined in the Variables tab
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/contenirizedapp
jobs:
- job: Phase_1
  displayName: Dockerized
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscriptionEndpoint: f0b94900-03aa-4474-a650-7cd7c1ebe70b
      azureContainerRegistry: '{"loginServer":"bhcontreg.azurecr.io", "id" : "/subscriptions/40932815-c53b-4939-8739-64ed4233f1cd/resourceGroups/BH-CONTAINERS/providers/Microsoft.ContainerRegistry/registries/bhcontreg"}'
      dockerFile: front/app/Dockerfile
      imageName: $(Build.Repository.Name)tmafront:$(Build.BuildId)
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: f0b94900-03aa-4474-a650-7cd7c1ebe70b
      azureContainerRegistry: '{"loginServer":"bhcontreg.azurecr.io", "id" : "/subscriptions/40932815-c53b-4939-8739-64ed4233f1cd/resourceGroups/BH-CONTAINERS/providers/Microsoft.ContainerRegistry/registries/bhcontreg"}'
      action: Push an image
      imageName: $(Build.Repository.Name)tmafront:$(Build.BuildId)
  - task: replacetokens@3
    displayName: Replace tokens in tmafront.yaml
    inputs:
      rootDirectory: front/app/
      targetFiles: tmafront.yaml
      escapeType: none
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: front/app/tmafront.yaml
...
