# Variable 'buildtrigered' was defined in the Variables tab
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/contenirizedapp
jobs:
- job: Phase_1
  displayName: Dockerized
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscriptionEndpoint: 
      azureContainerRegistry: ''
      dockerFile: back/Dockerfile
      imageName: $(Build.Repository.Name)tmaapi:$(Build.BuildId)
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: 
      azureContainerRegistry: ''
      action: Push an image
      imageName: $(Build.Repository.Name)tmaapi:$(Build.BuildId)
  - task: replacetokens@3
    displayName: Replace tokens in tmaapi.yaml
    inputs:
      rootDirectory: back
      targetFiles: tmaapi.yaml
      escapeType: none
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: back/tmaapi.yaml
...
