apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tmaapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: tmaapi
    spec:
      containers:
      - name: tmaapi
        image: bhcontreg.azurecr.io/tournamentmanagementapptmaapi:#{$(Release.Artifacts.{alias}.BuildId)}#
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tmaapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tmaapi